---


# Module documentation
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html


- name: Remove subscription-manager (RedHat)
  become: true
  when:
    - ansible_facts.distribution == "RedHat"
  ansible.builtin.package:
    name:
      - subscription-manager
    state: absent
