# - name: Cloud-Init Post Setup
#   become: true
#   gather_facts: false
#   # hosts: "{{ ansible_eda.event.payload.host | default(omit) }}"
#   hosts: ceph-[1-4].wcooke.me
#   roles:
#     - cloud_init_wait


- name: Cloud-init Post Setup
  become: true
  gather_facts: true
  # hosts: "{{ ansible_eda.event.payload.host | default(omit) }}"
  # hosts: control_planes
  # hosts: worker_nodes
  # hosts: aarch64_worker_nodes
  # hosts: control-amd64-2.iaas.wcooke.me
  hosts: cp1.iaas.wcooke.me
  serial: 100
  roles:
    - alloy
    - ca_certs
    - local_repos
    - aliases
    - autofs
    # - firefox
    - fstrim
    # - google_chrome
    - home_bin
    - insecure
    - logoff_timeout
    - logrotate
    - motd
    - networkmanager
    # - open_vm_tools
    - ps1_color
    # - qemu_server
    - ssh_public_key
    # - subscription_manager
    # - sudoers
    - systemd_journald
    - systemd_resolved
    - vim
  vars_files:
    - config.yml
    - private_config.yml
