---


vim_distro_info:
  Ubuntu:
    packages:
      - vim
      - vim-scripts
    vimrc_local_path: /etc/vim/vimrc.local


vim_family_info:
  Debian:
    packages:
      - vim
    vimrc_local_path: /etc/vimrc.local
  Gentoo:
    packages:
      - vim
    vimrc_local_path: /etc/vim/vimrc.local
  RedHat:
    packages:
      - vim
    vimrc_local_path: /etc/vimrc.local
