- name: Copy up-checker
  become: true
  ansible.builtin.template:
    dest: /usr/local/sbin/up-checker
    group: root
    mode: "0644"
    owner: root
    src: up-checker.j2


- name: Copy service file
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system/up-checker.service
    group: root
    mode: "0644"
    owner: root
    src: up-checker.service.j2


- name: Enable up-checker service
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: up-checker.service
    state: restarted
